language: node_js
services:
  - docker
node_js:
- '10'
cache:
  directories:
  - node_modules
before_script:
  - docker-compose up &
script:
  while :; do if [ $(docker ps | grep -i iv1201 | wc -l) = 2 ]; then docker exec app npm test --prefix backend; break; fi; done
