language: node_js
services:
  - docker
node_js:
- '10'
cache:
  directories:
  - node_modules
install:
  - docker-compose up
script:
  docker exec -it iv1201-project_app_1 npm test --prefix backend


